# Generated by Django 3.1 on 2020-08-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20200820_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
