# Generated by Django 3.0.8 on 2020-07-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='detail',
            new_name='details',
        ),
    ]
