# Generated by Django 3.1 on 2020-08-15 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200728_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='car.car')),
            ],
        ),
    ]
