# Generated by Django 3.1 on 2020-08-15 21:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20200815_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
