# Generated by Django 3.1 on 2020-08-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
