# Generated by Django 3.1 on 2020-08-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_auto_20200820_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Bag',
            field=models.CharField(blank=True, choices=[('Yes', 'True'), ('No', 'False')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('Yes', 'True'), ('No', 'False')], max_length=255),
        ),
    ]
