# Generated by Django 3.1 on 2020-08-16 00:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200816_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='aboutus',
            new_name='about',
        ),
        migrations.AddField(
            model_name='setting',
            name='ourhistory',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
