# Generated by Django 3.0.9 on 2020-08-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='youtube',
            new_name='linkedin',
        ),
    ]
