# Generated by Django 3.1 on 2020-08-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200822_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
